dwes_libros_login:
    path: /login
    defaults: { _controller: DWESLibrosBundle:Default:login }

dwes_libros_login_check:
    path: /login_check
    
dwes_libros_logout:
    path: /logout

dwes_libros_homepage:
    path:     /
    defaults: { _controller: DWESLibrosBundle:Default:index }

dwes_libros_registro:
    path: /registro/
    defaults: { _controller: DWESLibrosBundle:Default:registro }

dwes_libros_crearperfil:
    path: /crearperfil/
    defaults: { _controller: DWESLibrosBundle:Default:crearperfil }

dwes_libros_contacto:
    path: /contacto/
    defaults: { _controller: DWESLibrosBundle:Default:contacto }

dwes_libros_escribirhistoria:
    path: /escribirhistoria/{tipo}
    defaults: { _controller: DWESLibrosBundle:Default:escribirhistoria }

dwes_libros_perfil:
    path: /perfil/
    defaults: { _controller: DWESLibrosBundle:Default:perfil }

dwes_libros_publicadosBib:
    path: /publicadosBib/
    defaults: { _controller: DWESLibrosBundle:Default:publicadosBib }

dwes_libros_favoritoBib:
    path: /favoritoBib/
    defaults: { _controller: DWESLibrosBundle:Default:favoritoBib }

dwes_libros_deseadoBib:
    path: /deseadoBib/
    defaults: { _controller: DWESLibrosBundle:Default:deseadoBib }

dwes_libros_listaBib:
    path: /listaBib/
    defaults: { _controller: DWESLibrosBundle:Default:listaBib }
dwes_libros_ventaBib:
    path: /ventaBib/
    defaults: { _controller: DWESLibrosBundle:Default:ventaBib }

dwes_libros_ajustes:
    path: /ajustes/
    defaults: { _controller: DWESLibrosBundle:Default:ajustes }

dwes_libros_describirLib:
    path: /describirLib/
    defaults: { _controller: DWESLibrosBundle:Default:describirLib }

dwes_libros_capitulo:
    path: /capitulo/{idLibro}/{numCapitulo}
    defaults: { _controller: DWESLibrosBundle:Default:capitulo }
    requirements:
        page: \d+
dwes_libros_eliminarCap:
    path: /eliminarCap/{idLibro}/{numCapitulo}
    defaults: { _controller: DWESLibrosBundle:Default:eliminarCap }
    requirements:
        page: \d+

dwes_libros_nuevoCap:
    path: /nuevoCap/{idLibro}/
    defaults: { _controller: DWESLibrosBundle:Default:nuevoCap }
    requirements:
        page: \d+

dwes_libros_addbiblioteca:
    path: /addbiblioteca/{idLibro}/
    defaults: { _controller: DWESLibrosBundle:Default:addbiblioteca }
    requirements:
        page: \d+
dwes_libros_delbiblioteca:
    path: /delbiblioteca/{idLibro}/
    defaults: { _controller: DWESLibrosBundle:Default:delbiblioteca }
    requirements:
        page: \d+

dwes_libros_delfavoritos:
    path: /delfavoritos/{idLibro}/
    defaults: { _controller: DWESLibrosBundle:Default:delfavoritos }
    requirements:
        page: \d+

dwes_libros_addfavoritos:
    path: /addfavoritos/{idLibro}/
    defaults: { _controller: DWESLibrosBundle:Default:addfavoritos }
    requirements:
        page: \d+

dwes_libros_deldeseos:
    path: /deldeseos/{idLibro}/
    defaults: { _controller: DWESLibrosBundle:Default:deldeseos }
    requirements:
        page: \d+

dwes_libros_adddeseos:
    path: /adddeseos/{idLibro}/
    defaults: { _controller: DWESLibrosBundle:Default:adddeseos }
    requirements:
        page: \d+

dwes_libros_eliminarLib:
    path: /eliminarLib/{idLibro}
    defaults: { _controller: DWESLibrosBundle:Default:eliminarLib }
    requirements:
        page: \d+


dwes_libros_historia:
    path: /historia/{idLibro}/
    defaults: { _controller: DWESLibrosBundle:Default:historia }
    requirements:
        page: \d+

dwes_libros_suscripcion:
    path: /suscripcion/
    defaults: { _controller: DWESLibrosBundle:Default:suscripcion }

dwes_libros_perfilhistoria:
    path: /perfilhistoria/{idLibro}
    defaults: { _controller: DWESLibrosBundle:Default:perfilhistoria }
    requirements:
        page: \d+
        
dwes_libros_updateDescLibro:
    path: /updateDescLibro/{idLibro}
    defaults: { _controller: DWESLibrosBundle:Default:updateDescLibro }
    requirements:
        page: \d+

dwes_libros_addEnlaceLibro:
    path: /addEnlace/{idLibro}/
    defaults: { _controller: DWESLibrosBundle:Default:addEnlace }
    requirements:
        page: \d+

dwes_libros_eliminarEnlace:
    path: /eliminarEnlace/{idLibro}/{idEnlace}
    defaults: { _controller: DWESLibrosBundle:Default:eliminarEnlace }
    requirements:
        page: \d+

dwes_libros_editarEnlace:
    path: /editarEnlace/{idLibro}/{idEnlace}
    defaults: { _controller: DWESLibrosBundle:Default:editarEnlace }
    requirements:
        page: \d+

dwes_libros_updateInfoLibro:
    path: /updateInfoLibro/{idLibro}
    defaults: { _controller: DWESLibrosBundle:Default:updateInfoLibro }
    requirements:
        page: \d+        